version: '3.7'
services:
  # centos7 apache2.4.*(http2)
  web:
    build: ./web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    volumes:
      - ./code:/var/www/html
      - ./web/logs:/var/log/httpd
      - cert:/etc/ssl/private
    restart: always
    env_file: .env
  # php-fpm 
  php:
    build: ./php
    depends_on:
      - db
    ports:
      - "9000:9000"
    volumes:
      - ./code:/var/www/html
    restart: always
    env_file: .env
    # For site relation
    # extra_hosts:
    #   - teicon.lvh.me:$DOCKER_HOST_IP
  # mariaDB
  db:
    build: ./db
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
<<<<<<< HEAD
      - ./db/logs:/var/log/mysql
      - datastore:/var/lib/mysql
  # php Composer
  composer:
    image: composer

  # MailHog
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

=======
    - ./db/logs:/var/log/mysql
    - datastore:/var/lib/mysql
 
>>>>>>> a54de93b3657d8fec010f284a45e5fbad0010295
volumes:
  cert:
  datastore:
